//! Amalgamate the vendored jgm/djot.lua files into single bundled scripts.
//!
//! For each of {reader, writer}, the output is a self-contained Lua chunk:
//!   1. For each djot module, a `package.preload['djot.foo'] = function() ... end`
//!      wrapper that contains the module source. `require("djot.foo")` will run it.
//!   2. The main entry script (djot-reader.lua or djot-writer.lua) appended verbatim.
//!
//! Output: $OUT_DIR/djot_reader.lua, $OUT_DIR/djot_writer.lua
//!
//! The amalgamated files are included into the binary via include_str! in src/format.rs.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let vendor_dir = Path::new("scripts/vendor/djot");
    println!("cargo:rerun-if-changed=scripts/vendor/djot");
    println!("cargo:rerun-if-changed=scripts/vendor/lpeg");

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR"));

    // Compile LPeg against the same Lua headers mlua vendors. `lua-src`
    // is also an (indirect) dep of mlua-sys; Cargo dedupes so this only
    // adds the include-path lookup, no extra link artifact surfaces.
    let lua_artifacts = lua_src::Build::new().build(lua_src::Lua54);
    let lpeg = Path::new("scripts/vendor/lpeg");
    cc::Build::new()
        .files([
            "lpcap.c", "lpcode.c", "lpcset.c",
            "lpprint.c", "lptree.c", "lpvm.c",
        ].iter().map(|f| lpeg.join(f)))
        .include(lua_artifacts.include_dir())
        .warnings(false)
        .compile("lpeg");

    // Modules bundled into both reader and writer. The vendored djot-writer.lua
    // doesn't require() any djot modules, but shipping them doesn't hurt and
    // keeps the amalgamations symmetric.
    let modules: &[(&str, &str)] = &[
        ("djot", "djot.lua"),
        ("djot.ast", "djot/ast.lua"),
        ("djot.attributes", "djot/attributes.lua"),
        ("djot.block", "djot/block.lua"),
        ("djot.filter", "djot/filter.lua"),
        ("djot.html", "djot/html.lua"),
        ("djot.inline", "djot/inline.lua"),
        ("djot.json", "djot/json.lua"),
    ];

    amalgamate(
        vendor_dir,
        &out_dir.join("djot_reader.lua"),
        modules,
        "djot-reader.lua",
    );
    amalgamate(
        vendor_dir,
        &out_dir.join("djot_writer.lua"),
        modules,
        "djot-writer.lua",
    );
}

fn amalgamate(vendor: &Path, out: &Path, modules: &[(&str, &str)], main: &str) {
    let mut buf = String::new();
    buf.push_str("-- GENERATED by build.rs from scripts/vendor/djot/ — do not edit.\n");
    for (mod_name, rel_path) in modules {
        let src_path = vendor.join(rel_path);
        let source = fs::read_to_string(&src_path)
            .unwrap_or_else(|e| panic!("read {}: {e}", src_path.display()));
        // Choose a long-equals delimiter that's not present in the source.
        let mut eqs = 1;
        loop {
            let close = format!("]{}]", "=".repeat(eqs));
            if !source.contains(&close) {
                break;
            }
            eqs += 1;
        }
        let eq = "=".repeat(eqs);
        buf.push_str(&format!(
            "package.preload[{:?}] = assert(loadstring or load)([{eq}[\n",
            mod_name
        ));
        buf.push_str(&source);
        buf.push_str(&format!("\n]{eq}])\n"));
    }
    let main_src = fs::read_to_string(vendor.join(main))
        .unwrap_or_else(|e| panic!("read {}: {e}", main));
    buf.push('\n');
    buf.push_str(&main_src);
    fs::write(out, buf).unwrap_or_else(|e| panic!("write {}: {e}", out.display()));
}
